language: node_js
node_js: node
cache: npm
sudo: required
services:
  - docker

before_install:
  - docker build -t maxcutex/docker_react_frontend -f Dockerfile.dev . 

  script:
    - docker run maxcutex/docker_react_frontend npm run test -- --coverage
    